# Generated by Django 5.2.5 on 2025-09-13 03:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='creted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
