# Generated by Django 5.2.5 on 2025-11-12 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_postimage_creted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='allow_comments',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
