# Generated by Django 5.2.5 on 2025-11-19 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_ram_post_storage_post_battery_capacity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='brand',
        ),
    ]
