# Generated by Django 5.2.5 on 2025-11-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_post_phone_alter_post_content_alter_post_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='phone',
            field=models.CharField(blank=True, default=''),
        ),
    ]
